/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_apps_authenticator_AccountDb_OtpType */

#ifndef _Included_com_google_android_apps_authenticator_AccountDb_OtpType
#define _Included_com_google_android_apps_authenticator_AccountDb_OtpType
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
