/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_apps_authenticator_TotpCounter */

#ifndef _Included_com_google_android_apps_authenticator_TotpCounter
#define _Included_com_google_android_apps_authenticator_TotpCounter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_google_android_apps_authenticator_TotpCounter
 * Method:    getValueAtTimeNative
 * Signature: (JJJ)J
 */
JNIEXPORT jlong JNICALL Java_com_google_android_apps_authenticator_TotpCounter_getValueAtTimeNative
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
