/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_google_android_apps_authenticator_AccountDb */

#ifndef _Included_com_google_android_apps_authenticator_AccountDb
#define _Included_com_google_android_apps_authenticator_AccountDb
#ifdef __cplusplus
extern "C" {
#endif
#undef com_google_android_apps_authenticator_AccountDb_PROVIDER_UNKNOWN
#define com_google_android_apps_authenticator_AccountDb_PROVIDER_UNKNOWN 0L
#undef com_google_android_apps_authenticator_AccountDb_PROVIDER_GOOGLE
#define com_google_android_apps_authenticator_AccountDb_PROVIDER_GOOGLE 1L
/*
 * Class:     com_google_android_apps_authenticator_AccountDb
 * Method:    signNative
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_google_android_apps_authenticator_AccountDb_signNative
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
